name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
        
    - name: go-crossbuild
      # You may pin to the exact commit or the version.
      # uses: izumin5210/action-go-crossbuild@77788a44756d2fd2ba1eb9a4252b471397c63ffc
      uses: izumin5210/action-go-crossbuild@v1.0.0
      with:
        # An application name
        name: hearts
        # Space or comma separated list of GOARCH
        arch: arm64,amd64
        # Path to destination directory of built binaries
        #dest:
        # `-ldflags` to pass to go build
        #ldflags: # optional, default is 
        # `-tags` to pass to go build
        #tags: # optional, default is 
        # Space or comma separated list of GOOS
        os: darwin,linux,windows
        # Build target package
        #package: # optional, default is .
        # Version of github.com/Songmu/goxz
        #goxz-version: # optional, default is v0.4.1
    #- name: Download a Build Artifact
      #uses: actions/download-artifact@v3.0.0
      #with:
        # Artifact name
        #name: hearts-darwin-arm64
        # Destination path
        #path: # optional
    
    #- name: Build
      #run: go build -v hearts.go -o hearts-darwin-arm64
      
