name: hearts-darwin-arm64

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
        
    - name: Build
      run: env GOOS=darwin GOARCH=arm64 go build -o hearts-darwin-arm64 -v hearts.go
      
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.0
      with:
        # Artifact name
        name: hearts-darwin-arm64
        # Destination path
        #path: # optional
        
